import mongoose from "mongoose";

const { Schema } = mongoose;

const ApplicationSchema = Schema({
  RollNo: { type: String },
  Name: { type: String },
  Email: { type: String },
  Gender: { type: String, enum: ["Male", "Female"] },
  MobileNo: { type: String },
  Course: { type: String },
  Branch: { type: String },
  Semester: { type: Number },
  BackPaper: { type: Number },
  YearOfAdmission: { type: Number },
  Distance: { type: Number },
  BloodGroup: {
    type: String,
    enum: ["O+", "O-", "A+", "A-", "B+", "B-", "AB+", "AB-"],
  },
  Region: { type: String, enum: ["Delhi", "Outside Delhi"] },
  SGPA: { type: Number },
  ChronicProblems: { type: Array },
  Preferences: { type: Array },
  FatherName: { type: String },
  FatherMobileNo: { type: String },
  FatherEmail: { type: String },
  FatherOccupation: { type: String },
  FatherDesignation: { type: String },
  FatherOfficeAddress: { type: String },
  FatherOfficeNo: { type: String },
  MotherName: { type: String },
  MotherMobileNo: { type: String },
  MotherEmail: { type: String },
  MotherOccupation: { type: String },
  MotherDesignation: { type: String },
  MotherOfficeAddress: { type: String },
  MotherOfficeNo: { type: String },
  BackAccountNo: { type: String },
  BankAccountName: { type: String },
  BankName: { type: String },
  BankIFSC: { type: String },
  BankAddress: { type: String },
  HomeAddress: { type: String },
  HomeCity: { type: String },
  HomeState: { type: String },
  HomeCountry: { type: String },
  HomePincode: { type: String },
  CorrAddress: { type: String },
  CorrCity: { type: String },
  CorrState: { type: String },
  CorrCountry: { type: String },
  CorrPincode: { type: String },
  LocalGuardName: { type: String },
  LocalGuardAddress: { type: String },
  LocalGuardMobileNo: { type: String },
  LocalGuardEmail: { type: String },
  StudentSignature: { type: String },
  Discrepancy: { type: String },
  ProfilePic: { type: String },
});
